// Autogenerated from Pigeon (v26.2.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.flutter_playground

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object CustomCalendarApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class CalendarEventInput (
  val title: String? = null,
  val startDateMs: Long? = null,
  val endDateMs: Long? = null,
  val isAllDay: Boolean? = null,
  val description: String? = null,
  val url: String? = null,
  val location: String? = null,
  val remindersSeconds: List<Long?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CalendarEventInput {
      val title = pigeonVar_list[0] as String?
      val startDateMs = pigeonVar_list[1] as Long?
      val endDateMs = pigeonVar_list[2] as Long?
      val isAllDay = pigeonVar_list[3] as Boolean?
      val description = pigeonVar_list[4] as String?
      val url = pigeonVar_list[5] as String?
      val location = pigeonVar_list[6] as String?
      val remindersSeconds = pigeonVar_list[7] as List<Long?>?
      return CalendarEventInput(title, startDateMs, endDateMs, isAllDay, description, url, location, remindersSeconds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      title,
      startDateMs,
      endDateMs,
      isAllDay,
      description,
      url,
      location,
      remindersSeconds,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CalendarEventInput) {
      return false
    }
    if (this === other) {
      return true
    }
    return CustomCalendarApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class CustomCalendarApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CalendarEventInput.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CalendarEventInput -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CustomCalendarHostApi {
  fun createEvent(input: CalendarEventInput, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by CustomCalendarHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      CustomCalendarApiPigeonCodec()
    }
    /** Sets up an instance of `CustomCalendarHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CustomCalendarHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_playground.CustomCalendarHostApi.createEvent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val inputArg = args[0] as CalendarEventInput
            api.createEvent(inputArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CustomCalendarApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(CustomCalendarApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
