// Autogenerated from Pigeon (v26.2.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsCustomCalendarApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsCustomCalendarApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsCustomCalendarApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashCustomCalendarApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashCustomCalendarApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashCustomCalendarApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct CalendarEventInput: Hashable {
  var title: String? = nil
  var startDateMs: Int64? = nil
  var endDateMs: Int64? = nil
  var isAllDay: Bool? = nil
  var description: String? = nil
  var url: String? = nil
  var location: String? = nil
  var remindersSeconds: [Int64?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CalendarEventInput? {
    let title: String? = nilOrValue(pigeonVar_list[0])
    let startDateMs: Int64? = nilOrValue(pigeonVar_list[1])
    let endDateMs: Int64? = nilOrValue(pigeonVar_list[2])
    let isAllDay: Bool? = nilOrValue(pigeonVar_list[3])
    let description: String? = nilOrValue(pigeonVar_list[4])
    let url: String? = nilOrValue(pigeonVar_list[5])
    let location: String? = nilOrValue(pigeonVar_list[6])
    let remindersSeconds: [Int64?]? = nilOrValue(pigeonVar_list[7])

    return CalendarEventInput(
      title: title,
      startDateMs: startDateMs,
      endDateMs: endDateMs,
      isAllDay: isAllDay,
      description: description,
      url: url,
      location: location,
      remindersSeconds: remindersSeconds
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      startDateMs,
      endDateMs,
      isAllDay,
      description,
      url,
      location,
      remindersSeconds,
    ]
  }
  static func == (lhs: CalendarEventInput, rhs: CalendarEventInput) -> Bool {
    return deepEqualsCustomCalendarApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashCustomCalendarApi(value: toList(), hasher: &hasher)
  }
}

private class CustomCalendarApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return CalendarEventInput.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CustomCalendarApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CalendarEventInput {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CustomCalendarApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CustomCalendarApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CustomCalendarApiPigeonCodecWriter(data: data)
  }
}

class CustomCalendarApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CustomCalendarApiPigeonCodec(readerWriter: CustomCalendarApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CustomCalendarHostApi {
  func createEvent(input: CalendarEventInput, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CustomCalendarHostApiSetup {
  static var codec: FlutterStandardMessageCodec { CustomCalendarApiPigeonCodec.shared }
  /// Sets up an instance of `CustomCalendarHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CustomCalendarHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let createEventChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_playground.CustomCalendarHostApi.createEvent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createEventChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let inputArg = args[0] as! CalendarEventInput
        api.createEvent(input: inputArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createEventChannel.setMessageHandler(nil)
    }
  }
}
